CREATE OR REPLACE PROCEDURE XXPBSA_PR_LINES
AS
BEGIN
INSERT
INTO xx_req_po_stg
  (
    BATCH_ID,
    REQUISITION_TYPE,
    INTERFACE_SOURCE_CODE,
    DESTINATION_TYPE_CODE,
    ITEM_NAME,
    QUANTITY,
    AUTHORIZATION_STATUS,
    PREPARER_FULL_NAME,
    UOM_CODE,
    DESTINATION_ORGANIZATION,
    DELIVER_TO_LOCATION,
    DELIVER_TO_REQUESTOR,
    COST_CENTER,
    NATURAL_ACCOUNT,
    SUB_ANALYSIS_1,
    INTER_COMPANY,
    NEED_BY_DATE,
    OU_NAME,
    UNIT_PRICE,
    SUGGESTED_VENDOR_NAME,
    SUGGESTED_VENDOR_SITE
  )
SELECT prh_outter.PURCHASEREQUESTID BATCH_ID
  ,stg.REQUISITION_TYPE
  ,stg.INTERFACE_SOURCE_CODE
  ,stg.DESTINATION_TYPE_CODE
  ,prl_outter.PRODUCTID--ITEM_NAME
  ,prl_outter.QUANTITY--QUANTITY
  ,stg.AUTHORIZATION_STATUS
  ,stg.PREPARER_FULL_NAME
  ,REPLACE(prl_outter.UNIT, 'ECH')--UOM_CODE
  ,DESTINATION_ORGANIZATION
  ,DELIVER_TO_LOCATION
  ,DELIVER_TO_REQUESTOR
  ,COST_CENTER
  ,NATURAL_ACCOUNT
  ,SUB_ANALYSIS_1
  ,INTER_COMPANY
  ,NEED_BY_DATE
  ,OU_NAME
  ,prl_outter.LINETOTALCOST
  ,sup.VENDOR_NAME--SUGGESTED_VENDOR_NAME
  ,sup.VENDOR_SITE_CODE--SUGGESTED_VENDOR_SITE
FROM PURCHASE_REQUESTS_HEADER@DATABASE_LINK_EBS_APEX.LANKASATHOSA.ORG prh_outter,
  PURCHASE_REQUESTS_LINES@DATABASE_LINK_EBS_APEX.LANKASATHOSA.ORG prl_outter,
  (SELECT APS.VENDOR_NAME ,
    apss.VENDOR_SITE_CODE
  FROM PURCHASE_REQUESTS_LINES@DATABASE_LINK_EBS_APEX.LANKASATHOSA.ORG prl ,
    AP_SUPPLIERS aps ,
    AP_SUPPLIER_SITES_ALL apss
  WHERE 1            = 1
  AND prl.SUPPLIERID = aps.SEGMENT1
  AND apss.VENDOR_ID = aps.VENDOR_ID
  AND rownum         = 1
  ) sup,
  (SELECT * FROM xx_req_po_stg xrps WHERE rownum = 1) stg
WHERE prl_outter.PURCHASEREQUESTLINEID = prh_outter.PURCHASEREQUESTID;
END;