insert into MTL_SYSTEM_ITEMS_INTERFACE(ORGANIZATION_CODE, TEMPLATE_NAME, SEGMENT1, DESCRIPTION, PRIMARY_UOM_CODE, PURCHASING_ITEM_FLAG, PURCHASING_ENABLED_FLAG, PROCESS_FLAG, transaction_type, SECONDARY_UOM_CODE, TRACKING_QUANTITY_IND, SECONDARY_DEFAULT_IND)
select 'SIO' ORGANIZATION_CODE, TEMPLATE_NAME, 'ITEM00007666' SEGMENT1, 'TEST ITEM00007666' DESCRIPTION, 'ECH' PRIMARY_UOM_CODE, PURCHASING_ITEM_FLAG, PURCHASING_ENABLED_FLAG, 1 PROCESS_FLAG, 'CREATE' transaction_type
,'CSE' SECONDARY_UOM_CODE, 'PS' TRACKING_QUANTITY_IND, 'D' SECONDARY_DEFAULT_IND
from XXPBSA_ITEM_LOAD_TBL
where rownum = 1;
--0. run import items with default conc. parameters

select *
from MTL_SYSTEM_ITEMS_INTERFACE;

select *
from mtl_system_items_b
order by INVENTORY_ITEM_ID desc;

--PROCEDURES
--1. Item Create and assign to orgs
--2. Item assign to categories
--XXPBSA_PROCESS_ITEMS
--XXPBSA_AssignItmToCat